# Example GitHub Action Workflow
name: Push Latest Rules to Elastic Security Space

on:
  workflow_dispatch:
    inputs:
      overwrite:
        description: 'Overwrite existing rules'
        required: false
        default: 'true'
      overwrite_exceptions:
        description: 'Overwrite existing exceptions'
        required: false
        default: 'true'
      overwrite_action_connectors:
        description: 'Overwrite existing action connectors'
        required: false
        default: 'true'
      space:
        description: 'Kibana space to use (dev or prod)'
        required: false
        default: 'tmp'

jobs:
  sync-to-production:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip cache purge
        pip install tomlkit
        pip install .[dev]
        

    - name: Run the rule space updater
      run: python .github/scripts/toml-spacing.py

    # - name: Test rules before importing to kibana to Kibana
    #   run: |
    #     python -m detection_rules test
        
    - name: Import Rules to Kibana
      run: |
        FLAGS=""
        if [[ "${{ github.event_name }}" == "push" || "${{ inputs.overwrite }}" == "true" ]]; then
          FLAGS="$FLAGS --overwrite"
        fi
        if [[ "${{ github.event_name }}" == "push" || "${{ inputs.overwrite_exceptions }}" == "true" ]]; then
          FLAGS="$FLAGS --overwrite-exceptions"
        fi
        if [[ "${{ github.event_name }}" == "push" || "${{ inputs.overwrite_action_connectors }}" == "true" ]]; then
          FLAGS="$FLAGS --overwrite-action-connectors"
        fi
        SPACE="${{ inputs.space }}"
        SPACE_FLAG="--space $SPACE"
        python -m detection_rules kibana $SPACE_FLAG import-rules $FLAGS
      env:
        DR_KIBANA_URL: ${{ secrets.KIBANA_URL }}
        DR_API_KEY: ${{ secrets.ELASTIC_API_KEY }}
